[build]
rustc-wrapper = "sccache"

[check]
rustc-wrapper = "sccache"

[test]
rustc-wrapper = "sccache"

[bench]
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
