[package]
name = "flightrepl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Spice OSS Flight Query Repl"

[dependencies]
arrow.workspace = true
arrow-flight.workspace = true
parquet = "49.0.0"
clap.workspace = true
tokio.workspace = true
tonic = { workspace = true, default-features = false, features = [
  "transport",
  "tls",
  "tls-roots",
] }
regex = "1.10.3"
snafu = "0.8.0"
async-stream.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
datafusion.workspace = true
rustyline = "13.0.0"
candle-core = "0.4.1"
candle-examples = "0.4.1"
candle-transformers = "0.4.1"
tokenizers = "0.15.2"